### ISSUE TITLE
ImportError: cannot import name ‘BaseSettings’

### ISSUE THREAD

**Issue by kokocuk268** [Alexell/XEmpireBot#106]
Traceback (most recent call last): File "main.py", line 2, in <module> from bot.core import launcher

File "/root/XEmpireBot/bot/core/launcher.py", line 8, in <module> from bot.utils.settings import config, logo File "/root/XEmpireBot/bot/utils/settings.py", line 1, in <module> from pydantic_settings import BaseSettings, SettingsConfigDict ImportError: cannot import name 'BaseSettings' 
Ubuntu
![Uploading IMG_1160.jpeg…]()

**Comment by Alexell** [comment]
Убедитесь, что выполнили установку согласно инструкции и что версии модулей соответствуют тем, что в `requirements.txt`
