### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by seligor** [Alexell/XEmpireBot#39]
```
Select an action:
    1. Create session
    2. Run bot

> 2
2024-08-07 17:43:25 | INFO     | 84 | MuskEmpire | Trying to login...
2024-08-07 17:43:28 | SUCCESS  | 542 | MuskEmpire | Login successful
2024-08-07 17:43:32 | SUCCESS  | 554 | MuskEmpire | Offline bonus claimed: +16648023
2024-08-07 17:43:32 | INFO     | 563 | MuskEmpire | Level: 17 | Balance: 118 039 769 | Money per hour: 138 733 525
2024-08-07 17:43:32 | INFO     | 580 | MuskEmpire | Daily reward not available
2024-08-07 17:43:33 | INFO     | 284 | MuskEmpire | Taps started
2024-08-07 17:43:39 | SUCCESS  | 308 | MuskEmpire | Earned money: +4374 | Energy left: 11813
2024-08-07 17:43:45 | SUCCESS  | 308 | MuskEmpire | Earned money: +3780 | Energy left: 9923
2024-08-07 17:43:50 | SUCCESS  | 308 | MuskEmpire | Earned money: +2700 | Energy left: 8573
2024-08-07 17:43:55 | SUCCESS  | 308 | MuskEmpire | Earned money: +3996 | Energy left: 6575
2024-08-07 17:44:00 | SUCCESS  | 308 | MuskEmpire | Earned money: +3024 | Energy left: 5063
2024-08-07 17:44:07 | SUCCESS  | 308 | MuskEmpire | Earned money: +5184 | Energy left: 2471
2024-08-07 17:44:12 | SUCCESS  | 308 | MuskEmpire | Earned money: +2808 | Energy left: 1067
2024-08-07 17:44:12 | WARNING  | 292 | MuskEmpire | Taps stopped (not enough energy)
2024-08-07 17:44:13 | INFO     | 683 | MuskEmpire | Level: 17 | Balance: 119 607 115 | Money per hour: 138 733 525
2024-08-07 17:44:13 | ERROR    | 712 | MuskEmpire | Unknown error: list index out of range
2024-08-07 17:44:17 | INFO     | 563 | MuskEmpire | Level: 17 | Balance: 119 761 263 | Money per hour: 138 733 525
2024-08-07 17:44:17 | INFO     | 580 | MuskEmpire | Daily reward not available
2024-08-07 17:44:18 | INFO     | 683 | MuskEmpire | Level: 17 | Balance: 119 838 337 | Money per hour: 138 733 525
2024-08-07 17:44:18 | ERROR    | 712 | MuskEmpire | Unknown error: list index out of range
2024-08-07 17:44:22 | INFO     | 563 | MuskEmpire | Level: 17 | Balance: 119 953 948 | Money per hour: 138 733 525
2024-08-07 17:44:22 | INFO     | 580 | MuskEmpire | Daily reward not available
2024-08-07 17:44:23 | INFO     | 683 | MuskEmpire | Level: 17 | Balance: 119 992 485 | Money per hour: 138 733 525
2024-08-07 17:44:23 | ERROR    | 712 | MuskEmpire | Unknown error: list index out of range
2024-08-07 17:44:26 | INFO     | 563 | MuskEmpire | Level: 17 | Balance: 120 146 633 | Money per hour: 138 733 525
2024-08-07 17:44:26 | INFO     | 580 | MuskEmpire | Daily reward not available
2024-08-07 17:44:27 | INFO     | 683 | MuskEmpire | Level: 17 | Balance: 120 185 170 | Money per hour: 138 733 525
2024-08-07 17:44:27 | ERROR    | 712 | MuskEmpire | Unknown error: list index out of range
2024-08-07 17:44:31 | INFO     | 563 | MuskEmpire | Level: 17 | Balance: 120 339 318 | Money per hour: 138 733 525
2024-08-07 17:44:31 | INFO     | 580 | MuskEmpire | Daily reward not available
2024-08-07 17:44:32 | INFO     | 683 | MuskEmpire | Level: 17 | Balance: 120 377 855 | Money per hour: 138 733 525
2024-08-07 17:44:32 | ERROR    | 712 | MuskEmpire | Unknown error: list index out of range
^C2024-08-07 17:44:33 | INFO     | 13 | Bot stopped by user
Press any key to continue...

```

**Comment by khosrowkhazraei** [comment]
Same here

**Comment by lucasnguyen3979** [comment]
I have the same issue

![image](https://github.com/user-attachments/assets/87fcd354-de05-48ec-b24e-79af2e12632e)

**Comment by Alexell** [comment]
@seligor @lucasnguyen3979 
**If the issue is still relevant:**
- Update the bot to the latest version (command: `git pull`)
- Set **DEBUG_MODE=True** in your .env
- Run the bot with MANDATORY redirection of stdout to a file: `venv/bin/python3 main.py --action 2 >> app.log 2>&1`
- Monitor the contents of `app.log` and wait for errors (ERROR) to appear, then stop the bot
- Attach your `app.log` here for analysis and troubleshooting

**Comment by qazzaq666** [comment]
@Alexell дебаг выдает это при `list index out of range`

`2024-08-09 18:03:10 | ERROR    | 755 | yota | Unknown error: list index out of range
Traceback: Traceback (most recent call last):                                                                             File "C:\Users\Administrator\Desktop\FARM\XEmpireBot-main\bot\core\bot.py", line 731, in run                              skill = calculate_best_skill(skills=self.dbs['dbSkills'], ignored_skills=config.IGNORED_SKILLS, profile=full_profile, level=self.level, balance=self.balance, improve=improve_data)                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                           File "C:\Users\Administrator\Desktop\FARM\XEmpireBot-main\bot\utils\functions.py", line 112, in calculate_best_skill      best_skill = sorted(possible_skills, key=lambda x: x["ratio"])[-1]                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^                                                  IndexError: list index out of range 
`
