### ISSUE TITLE
После дневного периода выскакивает ошибка

### ISSUE THREAD

**Issue by almir20122** [Alexell/XEmpireBot#63]
```
socket.send() raised exception.
Task exception was never retrieved
future: <Task finished name='Task-35' coro=<Client.handle_updates() done, defined at D:\Documents\Python\XEmpireBot\venv\Lib\site-packages\pyrogram\client.py:535> exception=OSError(ConnectionResetError('Connection lost'))>
Traceback (most recent call last):
  File "D:\Documents\Python\XEmpireBot\venv\Lib\site-packages\pyrogram\client.py", line 569, in handle_updates
    channel=await self.resolve_peer(utils.get_channel_id(channel_id)),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\Python\XEmpireBot\venv\Lib\site-packages\pyrogram\methods\advanced\resolve_peer.py", line 111, in resolve_peer
    await self.invoke(
  File "D:\Documents\Python\XEmpireBot\venv\Lib\site-packages\pyrogram\methods\advanced\invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\Python\XEmpireBot\venv\Lib\site-packages\pyrogram\session\session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\Python\XEmpireBot\venv\Lib\site-packages\pyrogram\session\session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\Python\XEmpireBot\venv\Lib\site-packages\pyrogram\session\session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 7 more times]
  File "D:\Documents\Python\XEmpireBot\venv\Lib\site-packages\pyrogram\session\session.py", line 402, in invoke
    raise e from None
  File "D:\Documents\Python\XEmpireBot\venv\Lib\site-packages\pyrogram\session\session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\Python\XEmpireBot\venv\Lib\site-packages\pyrogram\session\session.py", line 340, in send
    raise e
  File "D:\Documents\Python\XEmpireBot\venv\Lib\site-packages\pyrogram\session\session.py", line 337, in send
    await self.connection.send(payload)
  File "D:\Documents\Python\XEmpireBot\venv\Lib\site-packages\pyrogram\connection\connection.py", line 69, in send
    await self.protocol.send(data)
  File "D:\Documents\Python\XEmpireBot\venv\Lib\site-packages\pyrogram\connection\transport\tcp\tcp_abridged.py", line 38, in send
    await super().send(
  File "D:\Documents\Python\XEmpireBot\venv\Lib\site-packages\pyrogram\connection\transport\tcp\tcp.py", line 104, in send
    raise OSError(e)
OSError: Connection lost
```

Ну я сам в ручную текст на русский переводил может в этом дело?

**Comment by Alexell** [comment]
В моем боте нету такого, как в ваших логах: `self.resolve_peer(utils.get_channel_id(channel_id))`
Я отвечаю только на вопросы о моем боте в том виде, в каком он здесь.
