### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Kolesnikov-R** [Alexell/XEmpireBot#81]
Здравствуйте, заполнил файл .env.
Создал сессию.
Запустил бот, пошли ошибка. 
В чем могут быть проблемы, подскажите, пожалуйста. 
![Снимок экрана от 2024-08-21 23-54-52](https://github.com/user-attachments/assets/60979133-c1ee-4f50-800b-7611c200feec)

**Comment by Alexell** [comment]
Включите дебаг в вашем `.env`, запустите бот с выводом в `app.log` (в readme написано, как это сделать) и приложите сюда файл.

**Comment by Kolesnikov-R** [comment]
> Включите дебаг в вашем `.env`, запустите бот с выводом в `app.log` (в readme написано, как это сделать), подождите, пока в файле появятся ошибки, потом остановите бота и приложите сюда файл.

2024-08-23 00:30:29 | INFO     | 82 | 1234 | Trying to login...
2024-08-23 00:30:30 | DEBUG    | 89 | 1234 | Login response:
{"success":true,"data":[]}
2024-08-23 00:30:30 | SUCCESS  | 656 | 1234 | Login successful
2024-08-23 00:30:30 | DEBUG    | 121 | 1234 | Full profile response:
{"success":false,"error":"platform"}
2024-08-23 00:30:30 | ERROR    | 152 | 1234 | Profile data error: 'data'
Traceback: Traceback (most recent call last):
  File "C:\Users\User\Downloads\XEmpireBot-main\bot\core\bot.py", line 123, in get_profile
    data = response_json['data']
           ~~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'

2024-08-23 00:30:33 | ERROR    | 925 | 1234 | Unknown error: 'profile'
Traceback: Traceback (most recent call last):
  File "C:\Users\User\Downloads\XEmpireBot-main\bot\core\bot.py", line 662, in run
    if self.user_id is None: self.user_id = int(full_profile['profile']['id'] or 0)
                                                ~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'profile'

2024-08-23 00:30:38 | DEBUG    | 142 | 1234 | Sync profile response:
{"success":false,"error":"platform"}
2024-08-23 00:30:38 | ERROR    | 152 | 1234 | Profile data error: 'data'
Traceback: Traceback (most recent call last):
  File "C:\Users\User\Downloads\XEmpireBot-main\bot\core\bot.py", line 144, in get_profile
    return response_json['data']
           ~~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'

2024-08-23 00:30:41 | ERROR    | 925 | 1234 | Unknown error: 'hero'
Traceback: Traceback (most recent call last):
  File "C:\Users\User\Downloads\XEmpireBot-main\bot\core\bot.py", line 677, in run
    self.update_level(level=int(profile['hero']['level'] or 0))
                                ~~~~~~~^^^^^^^^
KeyError: 'hero'

2024-08-23 00:30:47 | DEBUG    | 142 | 1234 | Sync profile response:
{"success":false,"error":"platform"}
2024-08-23 00:30:47 | ERROR    | 152 | 1234 | Profile data error: 'data'
Traceback: Traceback (most recent call last):
  File "C:\Users\User\Downloads\XEmpireBot-main\bot\core\bot.py", line 144, in get_profile
    return response_json['data']
           ~~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'

2024-08-23 00:30:50 | ERROR    | 925 | 1234 | Unknown error: 'hero'
Traceback: Traceback (most recent call last):
  File "C:\Users\User\Downloads\XEmpireBot-main\bot\core\bot.py", line 677, in run
    self.update_level(level=int(profile['hero']['level'] or 0))
                                ~~~~~~~^^^^^^^^
KeyError: 'hero'

2024-08-23 00:30:57 | DEBUG    | 142 | 1234 | Sync profile response:
{"success":false,"error":"platform"}
2024-08-23 00:30:57 | ERROR    | 152 | 1234 | Profile data error: 'data'
Traceback: Traceback (most recent call last):
  File "C:\Users\User\Downloads\XEmpireBot-main\bot\core\bot.py", line 144, in get_profile
    return response_json['data']
           ~~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'

2024-08-23 00:31:00 | ERROR    | 925 | 1234 | Unknown error: 'hero'
Traceback: Traceback (most recent call last):
  File "C:\Users\User\Downloads\XEmpireBot-main\bot\core\bot.py", line 677, in run
    self.update_level(level=int(profile['hero']['level'] or 0))
                                ~~~~~~~^^^^^^^^
KeyError: 'hero'

2024-08-23 00:31:06 | DEBUG    | 142 | 1234 | Sync profile response:
{"success":false,"error":"platform"}
2024-08-23 00:31:06 | ERROR    | 152 | 1234 | Profile data error: 'data'
Traceback: Traceback (most recent call last):
  File "C:\Users\User\Downloads\XEmpireBot-main\bot\core\bot.py", line 144, in get_profile
    return response_json['data']
           ~~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'

2024-08-23 00:31:09 | ERROR    | 925 | 1234 | Unknown error: 'hero'
Traceback: Traceback (most recent call last):
  File "C:\Users\User\Downloads\XEmpireBot-main\bot\core\bot.py", line 677, in run
    self.update_level(level=int(profile['hero']['level'] or 0))
                                ~~~~~~~^^^^^^^^
KeyError: 'hero'

2024-08-23 00:31:15 | DEBUG    | 142 | 1234 | Sync profile response:
{"success":false,"error":"platform"}
2024

**Comment by Alexell** [comment]
Ну очевидно, бот не смог авторизоваться в игре под вашим аккаунтом. Тут я ничем помочь не могу, это что-то у вас. Вы в игру то хоть с этого аккаунта заходили через официальный клиент?

**Comment by Kolesnikov-R** [comment]
> Ну очевидно, бот не смог авторизоваться в игре под вашим аккаунтом. Тут я ничем помочь не могу, это что-то у вас. Вы в игру то хоть с этого аккаунта заходили через официальный клиент?

Не знаю в чем причина, но на windows не завелось. 
А на Linux заработало. 
Спасибо!
