### ISSUE TITLE
utf-8 codec error

### ISSUE THREAD

**Issue by pharaoh347** [Alexell/XEmpireBot#97]
2024-09-01 12:31:51 | INFO     | 116 | Detected 10 sessions | 24 proxies
Traceback (most recent call last):
  File "/home/user1/XEmpireBot/main.py", line 11, in <module>
    asyncio.run(main())
  File "/home/user1/.pyenv/versions/3.10.0/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/user1/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/user1/XEmpireBot/main.py", line 6, in main
    await launcher.start()
  File "/home/user1/XEmpireBot/bot/core/launcher.py", line 131, in start
    tg_clients, session_data = await get_tg_clients()
  File "/home/user1/XEmpireBot/bot/core/launcher.py", line 82, in get_tg_clients
    session_data = get_session_data(session_names)
  File "/home/user1/XEmpireBot/bot/core/launcher.py", line 72, in get_session_data
    json.dump(data, file, ensure_ascii=False, indent=4)
  File "/home/user1/.pyenv/versions/3.10.0/lib/python3.10/json/__init__.py", line 180, in dump
    fp.write(chunk)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcd1' in position 2: surrogates not allowed

**Comment by Alexell** [comment]
You have invalid characters somewhere. If you use a file for proxy, make sure it is UTF-8 (without BOM). And I hope it did not occur to you to use non-standard characters for session names :)
